### ISSUE TITLE
Experimental Graph

### ISSUE THREAD

**Issue by BatmanChen** [ShiWuxuan/PRAKA#2]
同学您好，我仔细阅读你的论文、和是实验附录。你在论文中提出的方法非常有创新性，并取得了不错的结果。但我对实验部分的图表方面还有一些不太理解的地方，比如保存原型和真是原型可视化的结果方面，能否提供一下实验方面的代码给我参考呢。谢谢！

**Comment by ShiWuxuan** [comment]
很抱歉由于后面进行了一些额外的探索，导致之前可视化的代码已经遗失。关于原型的可视化，和常见的特征可视化一样我们使用的是普通的T-SNE。

**Comment by BatmanChen** [comment]
> 很抱歉由于后面进行了一些额外的探索，导致之前可视化的代码已经遗失。关于原型的可视化，和常见的特征可视化一样我们使用的是普通的T-SNE。
好的谢谢，我想问一下文中图4各个方法的不同阶段准确度对比图是需要将需要对比的方法都跑一次然后将数据进行汇总画图吗？

**Comment by ShiWuxuan** [comment]
是的，有的方法（比如我们的工作和SSRE）会在补充材料中提供准确率曲线的详细数据
